insert into tbl_tarif(id,price, tarifname) values(1,28.00,'day')
insert into tbl_tarif(id,price, tarifname) values(2,0.04,'minute')
insert into tbl_tarif(id,price, tarifname) values(3,20.00,'promoday')

insert into tbl_parking_space(id,location,available) values(50, 'Verdieping 5 Rechts',True)
insert into tbl_parking_space(id,location,available) values(51, 'Verdieping 5 Links',True)
insert into tbl_parking_space(id,location,available) values(52, 'Verdieping 5 Rechts',True)
insert into tbl_parking_space(id,location,available) values(53, 'Verdieping 5 Links',True)
insert into tbl_parking_space(id,location,available) values(54, 'Verdieping 5 Rechts',True)
insert into tbl_parking_space(id,location,available) values(55, 'Verdieping 5 Links',True)
insert into tbl_parking_space(id,location,available) values(56, 'Verdieping 5 Rechts',True)
insert into tbl_parking_space(id,location,available) values(57, 'Verdieping 5 Links',True)
insert into tbl_parking_space(id,location,available) values(58, 'Verdieping 5 Rechts',True)
insert into tbl_parking_space(id,location,available) values(59, 'Verdieping 5 Links',True)
insert into tbl_parking_space(id,location,available) values(60, 'Verdieping 6 Rechts',True)
insert into tbl_parking_space(id,location,available) values(61, 'Verdieping 6 Links',True)
insert into tbl_parking_space(id,location,available) values(62, 'Verdieping 6 Rechts',True)
insert into tbl_parking_space(id,location,available) values(63, 'Verdieping 6 Links',True)
insert into tbl_parking_space(id,location,available) values(64, 'Verdieping 6 Rechts',True)
insert into tbl_parking_space(id,location,available) values(65, 'Verdieping 6 Links',True)
insert into tbl_parking_space(id,location,available) values(66, 'Verdieping 6 Rechts',True)
insert into tbl_parking_space(id,location,available) values(67, 'Verdieping 6 Links',True)
insert into tbl_parking_space(id,location,available) values(68, 'Verdieping 6 Rechts',True)
insert into tbl_parking_space(id,location,available) values(69, 'Verdieping 6 Links',True)

insert into tbl_booking(id, vehicle_plate, start_time,total_price, parking_space_id) values(100, '2KLM001', '2023-05-10 08:05:05.000000',0.0,50)
insert into tbl_booking(id, vehicle_plate, start_time,total_price, parking_space_id) values(101, '2TEST02', '2023-05-11 08:05:05.000000',0.0,54)
insert into tbl_booking(id, vehicle_plate, start_time,total_price, parking_space_id) values(102, '2TEST03', '2023-05-12 08:05:05.000000',0.0,68)
insert into tbl_booking(id, vehicle_plate, start_time,total_price, parking_space_id) values(103, '2TEST04', '2023-05-13 08:05:05.000000',0.0,58)
insert into tbl_booking(id, vehicle_plate, start_time,total_price, parking_space_id) values(104, '2TEST05', '2023-05-14 08:05:05.000000',0.0,61)

